mod reload;
mod credits;
mod clearinv;
mod feed;
mod fly;
mod gma;
mod gmc;
mod gms;
mod gmsp;
mod god;
mod heal;
mod help;
mod seen;
mod tps;
mod uptime;
mod whois;
mod rules;
mod socials_common;
mod discord;
mod website;
mod store;
mod socials;
mod speed;
mod near;
mod kit;
mod suicide;
mod ping;
mod health;
mod coords;
mod playtime;
mod clearchat;
mod me;
mod time;
mod weather;
mod calc;
mod online;
mod flip;
mod pl;
mod i;
mod starterkit;

pub use reload::jinx_command_tree;
pub use credits::jinx_credits_command;
pub use clearinv::clearinv_command_tree;
pub use feed::feed_command_tree;
pub use fly::fly_command_tree;
pub use gma::gma_command_tree;
pub use gmc::gmc_command_tree;
pub use gms::gms_command_tree;
pub use gmsp::gmsp_command_tree;
pub use god::god_command_tree;
pub use heal::heal_command_tree;
pub use help::jinx_help_command;
pub use seen::seen_command_tree;
pub use tps::tps_command_tree;
pub use uptime::uptime_command_tree;
pub use whois::whois_command_tree;
pub use rules::rules_command_tree;
pub use discord::discord_command_tree;
pub use website::website_command_tree;
pub use store::store_command_tree;
pub use socials::socials_command_tree;
pub use gmc::creative_command_tree;
pub use gms::survival_command_tree;
pub use gmsp::spectator_command_tree;
pub use gma::adventure_command_tree;
pub use gmc::c_command_tree;
pub use gms::s_command_tree;
pub use gmsp::sp_command_tree;
pub use gma::a_command_tree;
pub use speed::speed_command_tree;
pub use near::near_command_tree;
pub use kit::{createkit_command_tree, kit_command_tree};
pub use suicide::suicide_command_tree;
pub use ping::ping_command_tree;
pub use health::jinx_health_command;
pub use coords::coords_command_tree;
pub use playtime::playtime_command_tree;
pub use clearchat::clearchat_command_tree;
pub use me::me_command_tree;
pub use time::{day_command_tree, night_command_tree};
pub use weather::{rain_command_tree, clear_command_tree, thunder_command_tree};
pub use calc::calc_command_tree;
pub use online::online_command_tree;
pub use flip::flip_command_tree;
pub use pl::plugins_alias_command_tree;
pub use i::give_alias_command_tree;
pub use starterkit::{starterkit_command_tree, delstarterkit_command_tree, apply_starterkit};
